version: 2
jobs:
  build:
    
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "build.gradle" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-demo-java-spring-{{ checksum "build.gradle" }}
      
      - run: ./gradlew check
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar